name: CI

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '11'

            - name: Build and package web application (skip tests)
              run: mvn clean package -DskipTests

            - name: Upload JAR artifact
              uses: actions/upload-artifact@v4
              with:
                name: app-jar
                path: target/*.jar

    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '11'
      
        - name: Install Chrome
          uses: browser-actions/setup-chrome@v1

        - name: Install ChromeDriver
          run: |
            sudo apt-get update
            sudo apt-get install -y chromium-chromedriver
            if [ ! -f /usr/bin/chromedriver ]; then
              sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
            fi

        - name: Start application
          run: nohup mvn spring-boot:run &

        - name: Run all tests (unit, integration, end-to-end)
          run: mvn verify

    qa:
      runs-on: self-hosted
      needs: test
      continue-on-error: true
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build project (required for SonarQube)
        run: mvn clean compile

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_TOKEN: squ_2e5e92982d966b8f4e8e3b2eb837a4d8a4747f28
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
